use_frameworks!

target 'SwiftyNominatim_Example' do
  pod 'SwiftyNominatim', :path => '../'

  target 'SwiftyNominatim_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
